#! /bin/sh

sxhkd &

# monitor init
autorandr --change 
xrandr --auto

# wm config
bspc config border_width        1 
bspc config window_gap          10
bspc config top_padding		    30

bspc config focused_border_color "#efcf9f"

bspc config split_ratio          0.52

bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true

# get array of connected monitor IDs (some monitor names throw errors out of bspc)
readarray -t monitors <<<"$(xrandr -q | grep " connected" | cut -d ' ' -f1)"
readarray -t monitor_ids <<<"$(bspc query -M)" 

# assign workspaces depending on number of attached monitors
if [ "${#monitors[@]}" = "1" ]
then 
	bspc monitor ${monitor_ids[0]} -d code notes web talk cad mail 7 8 9 0
    bspc rule -a STM32CubeIDE desktop='^1' follow=on
    bspc rule -a Joplin desktop='^2' follow=on
    bspc rule -a firefox desktop='^3' follow=on
    bspc rule -a Slack desktop='^4' follow=on
    bspc rule -a Kicad desktop='^5' follow=on 
    bspc rule -a Evolution desktop='^6' follow=on
else
	bspc monitor ${monitor_ids[0]} -d code notes web talk cad  
    bspc monitor ${monitor_ids[1]} -d mail 7 8 9 0
fi

# rules
bspc rule -a Zathura state=tiled

# startup 
feh --bg-fill ~/Nextcloud/Photos/winter_cabin.jpg
~/.config/polybar/bspwm_fullbar_launch.sh
picom --config ~/.config/picom/picom.conf -b &
blueman-applet &
dunst &
mopidy &
nextcloud &
light-locker &
xset s off
xset -dpms
